apiVersion : apps/v1
kind: Deployment
metadata:
  name: frontend-sword-king
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-sword-king
  template:
    metadata:
      labels:
        app: frontend-sword-king
    spec:
      containers:
      - image: gcr.io/fillcraft-swards/frontend_swards_img
        imagePullPolicy: Always
        name: frontend-sword-king
        ports:
        - containerPort: 4200
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
    name: frontend-sword-king
spec:
    type: LoadBalancer
    ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
    selector:
        app: frontend-sword-king
---

